const GET_POKEMONES = 'GET_POKEMONES';
const GET_POKEMON_ID = 'GET_POKEMON_ID';
const FILTER_TYPE_POKEMON = 'FILTER_TYPE_POKEMON';
const FILTER_ORIGIN_POKEMON = 'FILTER_ORIGIN_POKEMON';
const SORT_POKEMONS = 'SORT_POKEMONS';
const ADD_POKEMON = 'ADD_POKEMON';
const GET_POKEMON_NAME = 'GET_POKEMON_NAME';
const GET_TYPES = 'GET_TYPES';
const CLEAR_POKEMON_SEARCH = 'CLEAR_POKEMON_SEARCH';
const CLEAR_POKEMON_SPECS = 'CLEAR_POKEMON_SPECS';

export {
    GET_POKEMONES, 
    FILTER_TYPE_POKEMON,
    FILTER_ORIGIN_POKEMON,
    SORT_POKEMONS,
    ADD_POKEMON,
    GET_POKEMON_NAME,
    GET_TYPES,
    GET_POKEMON_ID,
    CLEAR_POKEMON_SEARCH,
    CLEAR_POKEMON_SPECS
};